#! /usr/bin/env python
import sys
import json
from optparse import OptionParser
from fabric.api import env 

from components.base import Component

env.key_filename = ['/Users/axolx/.ssh/axolx-base']
env.s3_bucket = 'backup.ombuweb.com'
env.gpg_key = 'A01D2B0D'
env.hosts_file = 'hosts.json'

def main():
    usage = "usage: %prog command"
    desc = "Run a command on a set of hosts"
    parser = OptionParser(description=desc, usage=usage)
    parser.add_option("-f", "--file", dest="filename",
                      help="Hosts manifest JSON file")
    parser.add_option("-b", "--bucket", dest="bucket",
                      help="Name of S3 bucket to place backups")
    (options, args) = parser.parse_args()

    if len(args) == 0:
        sys.exit("No command supplied")

    # overwrite option defaults
    if options.filename:
        env.hosts_file = options.filename
    if options.bucket:
        env.s3_bucket = options.bucket

    # overwrite option defaults
    for site in parse_sites(env.hosts_file):
        print '+ Processing site %s' % site["name"]
        for component in site["components"]:
            c = Component.factory(site["name"], component)
            for command in args:
                getattr(c, command)()

def parse_sites(jsonFile):
    try:
        f = open(jsonFile)
        return json.load(f)
    finally:
        f.close()

if __name__ == '__main__':
    sys.exit(main())
